### ISSUE TITLE
Problems with os-firewall

### ISSUE THREAD

**Issue by achetronic** [browningluke/terraform-provider-opnsense#28]
Hello there :) 

I have found several errors when dealing with firewall resources (`os-firewall` installed)

Let me expose them here:

## 1. Firewall NAT rules seems to be created but not shown anywhere:
example of resource:

```terraform
resource "opnsense_firewall_nat" "test_http_forwarding_rule" {
  interface = "wan"
  protocol  = "TCP"

  source = {
    net = "any"
    invert = false
  }

  destination = {
    net  = "wanip"
    port = 8080
  }

  target = {
    ip = "heimdal"
    port = 80
  }

  description = "[TEST] Forward HTTP traffic to Nginx Gateway"
}
```

#### Error 2: 

![Screenshot from 2023-09-06 11-56-03](https://github.com/browningluke/terraform-provider-opnsense/assets/61636487/7f39a6f0-0b99-4851-8ec2-4811d8e1cc77)

![test](https://github.com/browningluke/terraform-provider-opnsense/assets/61636487/78f59d3f-a720-43cf-85f2-37da7004251d)

## 2. Firewall aliases are correctly created but crashed after it:

example resource:
```terraform
resource "opnsense_firewall_alias" "kubernetes_lb_wireguard" {
  name = "test_kubernetes_lb_wireguard"

  type    = "host"
  content = [
    "192.168.2.63"
  ]

  stats       = true
  description = "[TEST] Custom name for Kubernetes' LoadBalancer exposing Wireguard"
}
```

First apply is fine, and the resource is created fine, but in the second apply:

![Screenshot from 2023-09-06 11-47-42](https://github.com/browningluke/terraform-provider-opnsense/assets/61636487/a1f7d171-bdd9-43f8-91a1-046a2a9e5479)

**Comment by browningluke** [comment]
Hi @achetronic, thank you for flagging these! I'll get these fixed as soon as I can.

**Comment by achetronic** [comment]
> Hi @achetronic, thank you for flagging these! I'll get these fixed as soon as I can.

No problem! I will rise the things I find 🫣😄

**Comment by browningluke** [comment]
Hey @achetronic

Thanks again for flagging this. I've finally got around to fixing them in the most recent release (v0.7.0).

For the first issue you flagged, the bug was a bit weird, the standard OPNsense firewall rules let you put special characters in the description, but the os-firewall plugin doesn't, so since you had `[TEST]` it was failing on the OPNsense end, but TF thought the resource was created. I've added validations now to prevent special characters in the description, so it should work correctly now.

For the second issue, it was a weird issue where the OPNsense API returned an empty array rather than an empty object, so the code failed to parse it. This should also be handled now.

Just a note, these resources use the os-firewall plugin, which puts the resources in a different place (i.e. not the regular places you find the rules in OPNsense), see below. Just thought I'd mention it since the first image you included is of the regular OPNsense firewall, rather than the os-firewall.

<img width="241" alt="image" src="https://github.com/browningluke/terraform-provider-opnsense/assets/24992944/f5c72077-91ac-4bc8-8884-8bfc14faf4f0">

Firewall > Automation > Filter / Source NAT is where you can find the resources

**Comment by browningluke** [comment]
I'll close this issue now, but feel to comment if you still run into these issues and I'll reopen it and investigate further.

**Comment by achetronic** [comment]
oh Thank you! @browningluke I will test this ASAP and will give you feedback for both, this one and this other: https://github.com/browningluke/terraform-provider-opnsense/issues/27#issuecomment-1763256160
