### ISSUE TITLE
Support for resource imports

### ISSUE THREAD

**Issue by ikaruswill** [browningluke/terraform-provider-opnsense#40]
Hi again!

**Background**
My conundrum is I already have an OPNsense instance up and running and I'd like to move a majority of its configuration to be managed by this terraform provider. 

I started off with creating aliases in Terraform but quickly realized that aliases, though unique by name, are not identified by the provider by name, but rather by the `id` attribute, and as such, new aliases of the same name, are identified as non-existent, thus results in a `create` action, which will fail the `terraform apply` as an alias with the same name already exists.

**Request**
- Would you consider adding support for importing existing resources so that existing setups can be migrated to this provider?
- If not, do you have any recommendations on the most painless method you know, of achieving the same goal?

**Comment by browningluke** [comment]
Hey there @ikaruswill.

> aliases, though unique by name, are not identified by the provider by name, but rather by the id attribute

Due to the way the OPNsense API works, every resource that gets created is assigned an `id`, which this provider just grabs and then uses - even for resources that have other unique attributes. I have considered allowing for imports using these unique attributes, but it would require some code changes to the `opnsense-go` library. I *currently* don't have plans to implement this, but if it truly would be a valuable feature, then I will consider it.

Regarding importing, although this provider doesn't *explicitly* include code to import resources (and isn't documented), TF can still handle importing if you provide the ID (see below). As this has to use the ID, grabbing it from OPNsense is a bit of a pain, but hopefully not too annoying. I should (and will) include this in the documentation in an upcoming release.


### Importing resources (an alias for example)

Editing a resource with the browser network monitor open lets you grab the ID of the resource. In this case: `8573647b-7cc5-4de4-812b-c5062a0c84b1`

<img width="1681" alt="image" src="https://github.com/browningluke/terraform-provider-opnsense/assets/24992944/0beac719-5b79-4e06-b812-a755f8c1318e">
<br/><br/>
Then in TF, importing into a resource should work like this:
<img width="894" alt="image" src="https://github.com/browningluke/terraform-provider-opnsense/assets/24992944/6b73d9a7-c4da-429d-b74f-5ebe49766597">

**Comment by browningluke** [comment]
The docs now include importing for all resources. Unfortunately it still involves using the OPNsense resource id, but hopefully it should be enough to get your existing setup imported.

Let me know if you run into anymore issues with this, and I'll re-open the issue!

**Comment by ikaruswill** [comment]
Thanks a lot. It was really helpful. I see the docs now in `0.10.0`. Importing with `id` is exactly what I was looking for, even if it's less convenient than using other visible unique identifiers, it's still a path forward! 

Modifying the `opnsense-go` library feels like a bit too much work for a functionality already present with the `id`. Appreciate your quick work, I'll proceed to import my existing setup. Have a good weekend!
